eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spotify:
  url:
    api: https://api.spotify.com/v1
    account: https://accounts.spotify.com/api
  limit: 10
  client-id:
  client-secret:
  credentials: client_credentials